### ISSUE TITLE
Push not works on IOS

### ISSUE THREAD

**Issue by alex-eri** [BelledonneCommunications/linhome-ios#4]
I have registration with sip.linhome.org proxy, but app not popup when i calling.

```
Contact: <sip:ri93jpy-0vhk@sip.linhome.org;gr=urn:uuid:37dfe34a-3e0b-00fe-bb84-d9626b5baff2>
User-Agent: Unknown (belle-sip/4.5.0) 

```
[Log ](https://www.linphone.org:444//tmp/610ffb20eb473_11ee45088e175b375a82.gz)

**Comment by alex-eri** [comment]
No 201 Push sent  on server

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome.
If this issue is still accurate could you please kindly re-test with latest 1.3 version ? 
the 1.3 version passed a deep test plan including that situation (dependent proxy config). 
if you are still encountering this issue can you please kindly reopen and attach a new log file ?
kind regards
