### ISSUE TITLE
[Feature] Show live view from a RTSP or HTTP (MJPEG) camera URL

### ISSUE THREAD

**Issue by nanosonde** [BelledonneCommunications/linhome-ios#8]
I have selected the device type "SIP security camera" during app setup on iOS
However, I am not able to enter the camera URL to show the live view of my video doorbell camera.

It would be nice to have RTSP and HTTP (MJPEG) video streaming.

There are a couple of video doorbell systems which do not offer video streams negotiated over SIP (with early media). 
Instead only audio is offered via SIP. The video stream is realized either by RTSP or HTTP (mostly MJPEG) streaming.

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome.
We have taken good note of your suggestion for potential integration in future releases.
Since this ticket is related to a feature development please contact the sales team through this online form : https://www.linhome.org/contact/ kind regards

**Comment by nanosonde** [comment]
LOL 2.5years later....
Not interested at all anymore....
